url: https://luizcarvalho.github.io
baseurl: ''

# Site settings
title: Luiz Carvalho.com
email: contato@luizcarvalho.com
description: Desenvolvimento de Sites, Apps, Chatbots, Palestras e Mentorias.
metatitle: Luiz Carvalho.com | Desenvolvimento de Sites, Apps, Chatbots, Palestras e Mentorias.
preview_image: https://res.cloudinary.com/drlko5ghb/image/upload/v1683120015/site_static/thumb.jpg

# Team names, titles and social links
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
my:
  name: Luiz Carvalho
  pic: 1
  position: Desenvolvimento, Palestras
  social_networks:
    - title: instagram
      url: http:/instagram.com/luizcarvalhobr
    - title: twitter
      url: http://twitter.com/LuizCarvalho
    - title: facebook
      url: http://facebook.com/luizcarvalho.br
    - title: stack-overflow
      url: http://pt.stackoverflow.com/users/292/luiz-carvalho
    - title: github
      url: http://github.com/luizcarvalho
    - title: linkedin
      url: https://www.linkedin.com/in/luizcarvalhodev
    - title: google-plus
      url: https://plus.google.com/+LuizCarvalhoDev/posts
    - title: slideshare
      url: http://www.slideshare.net/LuizCarvalhobr
    - title: facebook-messenger
      url: http:/m.me/luizcarvalhobr
    - title: whatsapp
      url: http://bit.ly/2WGofF7

social:
  - title: twitter
    url: http://twitter.com/LuizCarvalho
  - title: facebook
    url: http://facebook.com/luizcarvalho.br
  - title: stack-overflow
    url: http://pt.stackoverflow.com/users/292/luiz-carvalho
  - title: github
    url: http://github.com/luizcarvalho
  - title: linkedin
    url: https://www.linkedin.com/in/luizcarvalhodev
  - title: google-plus
    url: https://plus.google.com/+LuizCarvalhoDev/posts
  - title: slideshare
    url: http://www.slideshare.net/LuizCarvalhobr
  - title: facebook-messenger
    url: http:/m.me/luizcarvalhobr
  - title: whatsapp
    url: http://bit.ly/2WGofF7
  - title: instagram
    url: http:/instagram.com/luizcarvalhobr

# Postal address (add as many lines as necessary)
address:
  - line: Palmas, Tocantins, Brasil

# Build settings
markdown: kramdown
permalink: pretty

categories_filters: ['Mobile', 'Web', 'Design', 'Chatbots', 'Palestras']


firebase:
  storage_url: "https://firebasestorage.googleapis.com/v0/b/luizcarvalho-9a6c1.appspot.com/o/"
  token: "?alt=media&token=c773be8d-84db-4801-a469-bfee9ed49319"
