#!/bin/bash

# if anything in the _site/ subdirectory changed in the prior commit,
# push that directory to master for auto generation.
git diff-tree -r --name-only --no-commit-id code | grep '^_site/' &> /dev/null
if [ $? == 0 ]; then
  git push origin `git subtree split --prefix _site code 2> /dev/null`:master --force
fi
