#!/bin/bash
git push origin `git subtree split --prefix _site code 2> /dev/null`:master --force


# echo $DEPLOYING
# if [ -z "$DEPLOYING" ]; then
#   echo 'Deploying site...'
#   export DEPLOYING='yes'
#   git push origin `git subtree split --prefix _site code 2> /dev/null`:master --force
#   unset -v DEPLOYING
#   echo 'done!'
# fi
# exit 0
