source 'https://rubygems.org'
ruby '2.3.1'

gem 'jekyll'
gem 'rake'
gem 'tinypng' , :git => 'https://github.com/thomas07vt/tinypng.git'
gem 'pry'
gem 'mini_magick'
gem 'uglifier'
gem 'sass'
gem 'jekyll-assets'
gem 'dotenv'
